src/OrgChart.Web/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OrgChart.Core.Entities;
using OrgChart.Core.Interfaces;
using OrgChart.Core.Specifications;
using OrgChart.Infrastructure.Identity;
using OrgChart.Web.ViewModels.Organization;
using System.Linq;
using System.Threading.Tasks;

namespace OrgChart.Web.Controllers
{
    public class OrganizationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRepository<Organization> _organizationRepository;
        private readonly IAuthorizationService _authorizationService;

        public OrganizationController(
            UserManager<ApplicationUser> userManager,
            IRepository<Organization> organizationRepository,
            IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _organizationRepository = organizationRepository;
            _authorizationService = authorizationService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var specification = new OrganizationWithPeopleSpecification();
            var viewModel = _organizationRepository
                .List(specification)
                .Select(o => new OrganizationViewModel(o));

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Add() => View();

        [HttpPost]
        public IActionResult Add(AddOrganizationViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var organization = new Organization
            {
                UserId = _userManager.GetUserId(User),
                Name = model.Name
            };

            _organizationRepository.Add(organization);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddPerson(int organizationId)
        {
            var specification = new OrganizationWithPeopleSpecification(organizationId);
            var organization = _organizationRepository.GetBySpecification(specification);
            if (organization == null) return NotFound();

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, organization, Operations.Read);

            if (!authorizationResult.Succeeded) return Forbid();
            var viewModel = new AddPersonViewModel(organization);
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddPerson(AddPersonViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var specification = new OrganizationWithPeopleSpecification(model.OrganizationId);
            var organization = _organizationRepository.GetBySpecification(specification);

            if (organization == null) return BadRequest();

            var authorizationResult = await _authorizationService
                .AuthorizeAsync(User, organization, Operations.Update);

            if (!authorizationResult.Succeeded) return Forbid();

            organization.AddPerson(model.FirstName, model.LastName, model.EmailAddress,
                model.PhoneNumber, model.Title, model.ReportsToPersonID);

            _organizationRepository.Update(organization);

            return RedirectToAction(nameof(People), new { organizationId = organization.Id });
        }

        [HttpGet]
        public async Task<IActionResult> People(int organizationId)
        {
            var specification = new OrganizationWithPeopleSpecification(organizationId);
            var organization = _organizationRepository.GetBySpecification(specification);

            if (organization == null) return NotFound();

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, organization, Operations.Read);

            if (!authorizationResult.Succeeded) return Forbid();

            var viewModel = new PeopleViewModel();
            viewModel.OrganizationId = organization.Id;
            viewModel.People = organization.People.Select(p => new PersonViewModel(p));

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Chart(int organizationId)
        {
            var specification = new OrganizationWithPeopleSpecification(organizationId);
            var organization = _organizationRepository.GetBySpecification(specification);

            if (organization == null) return NotFound();

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, organization, Operations.Read);

            if (!authorizationResult.Succeeded) return Forbid();

            var people = organization.People
                .Select(p => new
                {
                    Id = p.Id.ToString(),
                    Name = (p.FirstName + " " + p.LastName).Trim(),
                    p.Title,
                    ReportsToId = p.ReportsTo?.Id.ToString() ?? ""
                });

            var viewModel = new ChartViewModel { PeopleJson = JsonConvert.SerializeObject(people) };
            return View(viewModel);
        }
    }
}

src/OrgChart.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <environment names="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment names="Production">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </environment>

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">OrgChart</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Organization" asp-action="Index">Organizations</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <form asp-controller="Account" asp-action="Logout" class="form-inline" method="post">
                            <span class="navbar-text">
                                @User.Identity.Name |
                            </span>
                            <button type="submit" class="btn btn-link nav-link nav-item">Log Out</button>
                        </form>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - OrgChart</p>
        </footer>
    </div>
    <environment names="Development">
        <script src="~/node_modules/jquery/dist/jquery.slim.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment names="Production">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>